# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 64a530ff69d9e5a305062e97f6c0f53e78ebe4e597c88e3ed82567985c7b613e57fc7ba3346534a70b34c6da164ed627a4b3f0a3184ec2112cde4032cab09aeb

test:
  secret_key_base: b6a1c2995418951d7be510c81414c2fa7549dfc7d0cbe4f6c9f1a83f49736a455599f2f72c7e768c370cdaf2278b90f8eb615cff6a1e948c01f9b3fae005c0ed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
